### ISSUE TITLE
Information on captured face landmark

### ISSUE THREAD

**Issue by GeorgeS2019** [georg-jung/FaceAiSharp#25]
There are few standards, wonder which one this project provides on the resolution of the facial landmark?

**Comment by georg-jung** [comment]
I assume you're interested in "How many and which points does `det.DetectFaces(img)[0].Landmarks` return?"?

FaceAiSharp currently uses [SCRFD](https://github.com/deepinsight/insightface/tree/master/detection/scrfd) for face detection and landmarks. SCRFD emits 5 facial landmark points, in this order:

- left eye center
- right eye center
- nose tip
- left mouth corner
- right mouth corner

FaceAiSharp is loosley prepared to be extended for usage with other models too. Abstractions like `IFaceLandmarksDetector` don't make any assumptions about what and how many landmarks are detected. `ArcFaceEmbeddingsGenerator.AlignFaceUsingLandmarks` does however currently assume it is called with SCRFD's points as an argument.

Feel free to re-open or discuss further if this doesn't answer your question.

**Comment by GeorgeS2019** [comment]
![image](https://github.com/georg-jung/FaceAiSharp/assets/49812372/15cc4cc7-ec91-40ab-98fa-031e0910e432)

**Comment by georg-jung** [comment]
The landmarks in the image you posted look similar to those in the [iBUG 300W dataset](https://ibug.doc.ic.ac.uk/resources/facial-point-annotations/). One widely used library that detects these 68 points is [dlib](http://dlib.net/face_landmark_detection.py.html). While it would certainly be possible to extend FaceAiSharp to support dlib-like landmarks, this feature is currently not implemented.
