### ISSUE TITLE
Exception when comparing faces

### ISSUE THREAD

**Issue by ShriN** [georg-jung/FaceAiSharp#59]
Hello,

We are using FaceAISharp to compare the faces of a person. We are using version 0.5.23 from nuget. We are using asp.net core .net 6.0. It works perfectly fine when we run through visual studio with IISExpress.

But when we deployed the same app on Azure as a web app, it throws the following error while comparing two faces.

The type initializer for 'Microsoft.ML.OnnxRuntime.NativeMethods' threw an exception.

We tried to find the library Microsoft.ML.OnnxRuntime.NativeMethods, but no luck,

Please share how to fix this issue.

**Comment by georg-jung** [comment]
Hey @ShriN,

could you share the full stacktrace and the section of your `csproj` which contains the `PackageReference`s? Could you also include details about your Azure setup, e.g. which specific service are you using and which OS is it based on?

**Comment by ShriN** [comment]
Hello georg-jung, 

Thanks for looking into the issue and contacting us. 

After some trial and error, surprisingly issue just disappeared and the app started working fine, we just reinstalled the Nuget package. So maybe something got missed in the initial package installation.

If somebody faces a similar kind of issue, it is worth trying to reinstall the package.

Thanks once again georg-jung,!

**Comment by georg-jung** [comment]
Okay, great to hear it works for you!
